#!/usr/bin/env bash
# Build the TensorFold lane image from upstream + the patches in patches/.
#
# TensorFold ships as a pip package, not a container image, so this Dockerfile installs it from the
# pinned commit and then applies our two patches on top.
#
# The two lanes must produce IDENTICAL tokens for identical input — that is the whole premise of
# shipping them side by side. The ordered-FP32 reducer is bit-identical to the original Python
# chain (210/210 bitwise, eager + CUDA graph, adversarial/subnormal/signed-zero, real production
# N 320/2560/3072/6144; 210/210 on the manual PTX dependency review), so this build changes speed
# and nothing else. If a token_sha ever differs between lanes, stop and investigate.
#
#   ./build-tensorfold.sh                 # build the pinned tag
#   TENSORFOLD_TAG=my-experiment ./build-tensorfold.sh
#
# Runs on the HEAD box. Needs docker + git. The base is ~24 GB the first time.
set -euo pipefail
cd "$(dirname "$0")"

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/ashhart/TensorFold.git}"
UPSTREAM_SHA="${UPSTREAM_SHA:-9cd52ab4daba68ddd09be89be8f23ad43175e821}"   # release 0.5.0
TAG="${TENSORFOLD_TAG:-tensorfold/tensorfold:0.5.0-ct-tp2}"
BUILD_DIR="${BUILD_DIR:-.build-tensorfold}"
# The vLLM lane's image is nvcr.io/nvidia/pytorch:26.07-py3. Reusing it keeps the two lanes on the
# same CUDA/torch stack, so a difference in output can never be a torch-version artifact.
BASE_IMAGE="${BASE_IMAGE:-nvcr.io/nvidia/pytorch:26.07-py3}"

echo "· upstream  : $UPSTREAM_URL @ $UPSTREAM_SHA"
echo "· base image: $BASE_IMAGE   (same stack as the vLLM lane, on purpose)"
echo "· image     : $TAG"
echo "· build in  : $BUILD_DIR   (safe to delete; recreated every run)"

command -v docker >/dev/null || { echo "✗ docker is required"; exit 1; }
command -v git    >/dev/null || { echo "✗ git is required"; exit 1; }

for p in patches/tensorfold-qwen4exp-ct-tp2.patch patches/tensorfold-ordered-f32-reducer.patch; do
  [ -f "$p" ] || { echo "✗ missing $p — run from the repo root"; exit 1; }
done

# 1. a pristine export of the exact pinned commit (never a branch: a floating ref would make this
#    image unreproducible, which is the one thing a published recipe cannot afford)
echo "· fetching upstream"
rm -rf "$BUILD_DIR"; mkdir -p "$BUILD_DIR/src"
git init -q "$BUILD_DIR/src"
git -C "$BUILD_DIR/src" remote add origin "$UPSTREAM_URL"
git -C "$BUILD_DIR/src" fetch -q --depth 1 origin "$UPSTREAM_SHA"
git -C "$BUILD_DIR/src" checkout -q FETCH_HEAD
echo "  got $(git -C "$BUILD_DIR/src" rev-parse HEAD)"

# 2. apply the CT/TP2 port, then the reducer. A --check failure on an already-applied patch is a
#    re-apply, not a missing patch — say which, instead of failing on something harmless.
for p in patches/tensorfold-qwen4exp-ct-tp2.patch patches/tensorfold-ordered-f32-reducer.patch; do
  echo "· applying $p"
  if ! git -C "$BUILD_DIR/src" apply --check "$p" 2>/dev/null; then
    if git -C "$BUILD_DIR/src" apply --reverse --check "$p" 2>/dev/null; then
      echo "  ⚠ $p is ALREADY applied to $UPSTREAM_SHA — continuing (re-apply, not a failure)."
    else
      echo "✗ $p does not apply to $UPSTREAM_SHA. Upstream moved, or the patch needs rebasing."
      exit 1
    fi
  else
    git -C "$BUILD_DIR/src" apply "$p"
  fi
done
echo "· result:"
git -C "$BUILD_DIR/src" diff --stat HEAD | tail -1

# 3. build. Upstream has no Dockerfile of its own — it is a pip package — so we generate one that
#    installs the patched tree into the same CUDA base the vLLM lane uses.
cat > "$BUILD_DIR/Dockerfile" <<DOCKERFILE
# Generated by build-tensorfold.sh — edit the script, not this file.
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends git python3 python3-pip \\
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY src/ /src/
RUN python3 -m pip install --no-cache-dir -e .

# Fail the BUILD, not the first request, if the entrypoint or the patched reducer is absent.
RUN command -v tensorfold >/dev/null || (echo "tensorfold entrypoint missing after install" && exit 1)
RUN python3 -c "from tensorfold.families.qwen4_exp.cuda import bf16; \\
    assert hasattr(bf16,'configure_f32_reduction'), 'ordered-FP32 reducer did not land'"

ENTRYPOINT ["tensorfold"]
DOCKERFILE

echo "· building (pulls ~24 GB the first time)"
docker build -t "$TAG" "$BUILD_DIR"

echo
echo "✓ built $TAG"
echo
echo "  next:  ENGINE=tensorfold ./run.sh                       # the lane uses this image"
echo "  verify both lanes agree on identical input — they must produce the same token_sha:"
echo "    ENGINE=vllm       ./run.sh && curl -s localhost:8888/v1/chat/completions ..."
echo "    ENGINE=tensorfold ./run.sh && curl -s localhost:8888/v1/chat/completions ..."
